CREATE TABLE t_customer(
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(20),
  gender VARCHAR(10),
  telephone VARCHAR(20)
)

CREATE TABLE t_user(
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(20),
  PASSWORD VARCHAR(20)
)
CREATE TABLE t_order(
  id INT PRIMARY KEY AUTO_INCREMENT,
  orderno VARCHAR(20),
  productname VARCHAR(50),
  user_id INT
)